### ISSUE TITLE
IT:3 Setup dynamic routing for all movies

### ISSUE THREAD

**Issue by MarchCorbin** [MarchCorbin/amy-corbin-rancidtomatillos#9]
Setup routing and error handling for all movie details pages.
- [ ] Move between pages while holding onto user information
- [ ] Login Page back to homePage while carrying user info with us
- [ ] location.history?

**Comment by amykarnaze** [comment]
- [ ] Move between pages while holding onto user information
- [ ] Login Page back to homePage while carrying user info with us
- [ ] location.history?
